"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import SharedNavbar from "@/components/SharedNavbar";

const BACKEND = process.env.NEXT_PUBLIC_BACKEND_URL || "http://localhost:8000";

type ScoreData = {
  score?: number;
  confidence?: number;
  status?: string;
  summary?: string;
  recommendation?: string;
  [key: string]: unknown;
};

type AnalysisPayload = {
  analysis_id: number;
  status: string;
  outputs?: {
    legal_json?: ScoreData;
    risk_json?: ScoreData;
    valuation_json?: ScoreData;
    final_json?: ScoreData;
  };
};

function getNumericScore(value: unknown): number | null {
  if (typeof value === "number" && Number.isFinite(value)) {
    return Math.max(0, Math.min(100, Math.round(value)));
  }
  if (typeof value === "string") {
    const parsed = Number(value);
    if (Number.isFinite(parsed)) {
      return Math.max(0, Math.min(100, Math.round(parsed)));
    }
  }
  return null;
}

export default function PropertyReportPage() {
  const params = useParams<{ analysisId: string }>();
  const analysisId = params?.analysisId || "";

  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [analysis, setAnalysis] = useState<AnalysisPayload | null>(null);

  useEffect(() => {
    if (!analysisId) return;

    let mounted = true;

    const run = async () => {
      setLoading(true);
      setError("");
      try {
        const res = await fetch(`${BACKEND}/analyze/${analysisId}`);
        const data = await res.json();
        if (!res.ok) {
          throw new Error(data?.detail || "Failed to load analysis report");
        }
        if (mounted) {
          setAnalysis(data as AnalysisPayload);
        }
      } catch (e) {
        if (mounted) {
          setError(e instanceof Error ? e.message : "Unexpected error while loading report");
        }
      } finally {
        if (mounted) {
          setLoading(false);
        }
      }
    };

    run();

    return () => {
      mounted = false;
    };
  }, [analysisId]);

  const legal = analysis?.outputs?.legal_json || {};
  const risk = analysis?.outputs?.risk_json || {};
  const valuation = analysis?.outputs?.valuation_json || {};
  const final = analysis?.outputs?.final_json || {};

  const legalScore = getNumericScore(legal.score ?? legal.confidence);
  const riskScore = getNumericScore(risk.score ?? risk.confidence);
  const valuationScore = getNumericScore(valuation.score ?? valuation.confidence);

  const overallRiskLabel = useMemo(() => {
    const riskLevel = String(final.risk_level || final.overall_risk || "").toLowerCase();
    if (riskLevel.includes("low")) return "Low";
    if (riskLevel.includes("high")) return "High";
    if (riskLevel.includes("medium")) return "Medium";
    return "Unknown";
  }, [final]);

  const legalBadge = String(legal.document_validity || legal.risk_level || legal.status || "unknown").replaceAll("_", " ");
  const riskBadge = String(risk.risk_level || risk.status || "unknown").replaceAll("_", " ");
  const valuationBadge = String(valuation.price_fairness || valuation.status || "unknown").replaceAll("_", " ");
  const gradeLabel = String(final.go_no_go || final.decision || "unknown").replaceAll("_", " ");

  const summaryText = String(
    final.summary ||
      final.executive_summary ||
      final.recommendation ||
      "Comprehensive property due diligence generated by the analysis pipeline."
  );

  const reportHtmlUrl = `${BACKEND}/reports/${analysisId}/html`;
  const reportTxtUrl = `${BACKEND}/reports/${analysisId}/txt`;
  const reportPdfUrl = `${BACKEND}/reports/${analysisId}/pdf`;

  return (
    <div className="bg-slate-50 text-slate-900 min-h-screen">
      <SharedNavbar active="my-reports" />

      <main className="md:ml-64 pt-10 pb-20 px-8 min-h-screen">
        <section className="max-w-6xl mx-auto mb-12">
          {loading && (
            <div className="rounded-2xl bg-white border border-slate-200 p-8 text-sm text-slate-600">Loading report #{analysisId}...</div>
          )}

          {!loading && error && (
            <div className="rounded-2xl bg-red-50 border border-red-200 p-8 text-sm text-red-700">{error}</div>
          )}

          {!loading && !error && (
            <>
              <div className="flex flex-col md:flex-row md:items-end justify-between gap-8 bg-slate-100 p-10 rounded-2xl">
                <div className="space-y-4">
                  <div className="inline-flex items-center gap-2 px-3 py-1 bg-cyan-100 rounded-full text-cyan-900 font-semibold text-xs uppercase tracking-wider">
                    <span className="material-symbols-outlined text-sm">verified</span> Verified Analysis
                  </div>
                  <h1 className="text-4xl font-extrabold text-blue-950 tracking-tight leading-tight">Property Analysis Report</h1>
                  <p className="text-slate-600 font-medium flex items-center gap-2">
                    <span className="material-symbols-outlined">calendar_today</span>
                    Report Generated • ID: #TQ-{analysisId} • Status: {analysis?.status || "completed"}
                  </p>
                </div>
                <div className="flex flex-col items-center gap-3">
                  <div className="relative w-32 h-32 flex items-center justify-center rounded-full border-[6px] border-emerald-100 bg-white shadow-xl">
                    <div className="text-center">
                      <span className="block text-3xl font-black text-emerald-600">{overallRiskLabel}</span>
                      <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Risk Score</span>
                    </div>
                  </div>
                  <span className="text-xs font-bold text-emerald-700 bg-emerald-50 px-3 py-1 rounded-full border border-emerald-100">{gradeLabel}</span>
                </div>
              </div>

              <section className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-6 mt-6 mb-12">
                <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200/70 flex flex-col h-full">
                  <div className="flex justify-between items-start mb-6">
                    <div>
                      <h3 className="text-lg font-bold text-blue-950 mb-1">Legal Analysis</h3>
                      <span className="text-xs font-bold text-emerald-600 uppercase tracking-tighter">{legalBadge}</span>
                    </div>
                    <div className="text-2xl font-black text-blue-950">{legalScore ?? "N/A"}{legalScore !== null && <span className="text-sm font-medium text-slate-400">/100</span>}</div>
                  </div>
                  <div className="space-y-4 flex-grow">
                    <ul className="space-y-3">
                      <li className="flex items-start gap-3">
                        <span className="material-symbols-outlined text-emerald-500 text-sm mt-1">check_circle</span>
                        <span className="text-sm font-medium text-slate-600">{String(legal.summary || legal.status || "Legal checks completed")}</span>
                      </li>
                    </ul>
                  </div>
                </div>

                <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200/70 flex flex-col h-full">
                  <div className="flex justify-between items-start mb-6">
                    <div>
                      <h3 className="text-lg font-bold text-blue-950 mb-1">Risk Assessment</h3>
                      <span className="text-xs font-bold text-emerald-600 uppercase tracking-tighter">{riskBadge}</span>
                    </div>
                    <div className="text-2xl font-black text-blue-950">{riskScore ?? "N/A"}{riskScore !== null && <span className="text-sm font-medium text-slate-400">/100</span>}</div>
                  </div>
                  <div className="space-y-4 flex-grow">
                    <ul className="space-y-3">
                      <li className="flex items-start gap-3">
                        <span className="material-symbols-outlined text-emerald-500 text-sm mt-1">trending_up</span>
                        <span className="text-sm font-medium text-slate-600">{String(risk.summary || risk.status || "Risk profile generated")}</span>
                      </li>
                    </ul>
                  </div>
                </div>

                <div className="bg-white p-8 rounded-2xl shadow-sm border border-slate-200/70 flex flex-col h-full">
                  <div className="flex justify-between items-start mb-6">
                    <div>
                      <h3 className="text-lg font-bold text-blue-950 mb-1">Valuation</h3>
                      <span className="text-xs font-bold text-amber-700 uppercase tracking-tighter">{valuationBadge}</span>
                    </div>
                    <div className="text-2xl font-black text-blue-950">{valuationScore ?? "N/A"}{valuationScore !== null && <span className="text-sm font-medium text-slate-400">/100</span>}</div>
                  </div>
                  <div className="space-y-6 flex-grow">
                    <div className="bg-slate-100 p-4 rounded-xl">
                      <p className="text-[10px] font-black text-slate-500 uppercase tracking-widest mb-1">Estimated Value</p>
                      <p className="text-lg font-bold text-blue-950">{String(valuation.estimated_value || valuation.value_range || "Available in downloadable report")}</p>
                    </div>
                    <ul className="space-y-3">
                      <li className="flex items-start gap-3">
                        <span className="material-symbols-outlined text-amber-700 text-sm mt-1">stars</span>
                        <span className="text-sm font-medium text-slate-600">{String(valuation.summary || valuation.status || "Valuation benchmark completed")}</span>
                      </li>
                    </ul>
                  </div>
                </div>
              </section>

              <section className="max-w-6xl mx-auto">
                <div className="w-full bg-gradient-to-br from-blue-950 to-blue-800 text-amber-100 py-6 rounded-2xl shadow-lg flex items-center justify-center gap-4 transition-all">
                  <span className="material-symbols-outlined font-bold">download</span>
                  <a href={reportPdfUrl} target="_blank" rel="noreferrer" className="text-lg font-black tracking-widest uppercase">Download PDF Full Report</a>
                </div>
                <div className="mt-4 flex flex-wrap gap-3 justify-center">
                  <a href={reportHtmlUrl} target="_blank" rel="noreferrer" className="px-4 py-2 rounded-lg text-sm font-bold bg-white border border-slate-300 text-blue-900">Open HTML</a>
                  <a href={reportTxtUrl} target="_blank" rel="noreferrer" className="px-4 py-2 rounded-lg text-sm font-bold bg-white border border-slate-300 text-blue-900">Open TXT</a>
                </div>
                <p className="text-center mt-6 text-slate-400 text-xs font-medium italic">{summaryText}</p>
              </section>
            </>
          )}
        </section>
      </main>
    </div>
  );
}
